version: '3'

services:
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
  tuya_backend:
    container_name: backend-tuya
    image: juansedo/tuya-credit-be:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 3000:3000
    environment:
      - TYPEORM_HOST=
      - TYPEORM_USERNAME=
      - TYPEORM_PASSWORD=
      - TYPEORM_DATABASE=
      - BACKEND_BASE_URL=